<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AoELauncher</AssemblyName>
    <RootNamespace>AoELauncher</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationIcon>AoE.ico</ApplicationIcon>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>
