<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net48</TargetFramework>
	<UseWindowsForms>true</UseWindowsForms>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<LangVersion>10.0</LangVersion>
	<AssemblyName>AoELauncher</AssemblyName>
	<RootNamespace>AoELauncher</RootNamespace>
	<ApplicationIcon>AoE.ico</ApplicationIcon>
	<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
	</PropertyGroup>
</Project>